[general]
import = [
    "~/.config/alacritty/themes/themes/github_light_tritanopia.toml"
]

[env]
TERM = "xterm-256color"

decorations = "Buttonless"

[font]
normal.family = "Inconsolata Nerd Font"
size = 10
